development:
  adapter: sqlite3
  encoding: unicode
  database: login
  pool: 5
  username: landontwith
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: myapp
  password: password1
